# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mahesh/slam-phase2/slam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mahesh/slam-phase2/slam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahesh/slam-phase2/slam/CMakeFiles /home/mahesh/slam-phase2/slam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahesh/slam-phase2/slam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3d_ptest

# Build rule for target.
3d_ptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3d_ptest
.PHONY : 3d_ptest

# fast build rule for target.
3d_ptest/fast:
	$(MAKE) -f CMakeFiles/3d_ptest.dir/build.make CMakeFiles/3d_ptest.dir/build
.PHONY : 3d_ptest/fast

#=============================================================================
# Target rules for targets named 3d_test

# Build rule for target.
3d_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3d_test
.PHONY : 3d_test

# fast build rule for target.
3d_test/fast:
	$(MAKE) -f CMakeFiles/3d_test.dir/build.make CMakeFiles/3d_test.dir/build
.PHONY : 3d_test/fast

#=============================================================================
# Target rules for targets named feature_test

# Build rule for target.
feature_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 feature_test
.PHONY : feature_test

# fast build rule for target.
feature_test/fast:
	$(MAKE) -f CMakeFiles/feature_test.dir/build.make CMakeFiles/feature_test.dir/build
.PHONY : feature_test/fast

#=============================================================================
# Target rules for targets named features2d

# Build rule for target.
features2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 features2d
.PHONY : features2d

# fast build rule for target.
features2d/fast:
	$(MAKE) -f features2d/CMakeFiles/features2d.dir/build.make features2d/CMakeFiles/features2d.dir/build
.PHONY : features2d/fast

#=============================================================================
# Target rules for targets named matchlib

# Build rule for target.
matchlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matchlib
.PHONY : matchlib

# fast build rule for target.
matchlib/fast:
	$(MAKE) -f matchlib/CMakeFiles/matchlib.dir/build.make matchlib/CMakeFiles/matchlib.dir/build
.PHONY : matchlib/fast

test/feature_test.o: test/feature_test.cpp.o
.PHONY : test/feature_test.o

# target to build an object file
test/feature_test.cpp.o:
	$(MAKE) -f CMakeFiles/feature_test.dir/build.make CMakeFiles/feature_test.dir/test/feature_test.cpp.o
.PHONY : test/feature_test.cpp.o

test/feature_test.i: test/feature_test.cpp.i
.PHONY : test/feature_test.i

# target to preprocess a source file
test/feature_test.cpp.i:
	$(MAKE) -f CMakeFiles/feature_test.dir/build.make CMakeFiles/feature_test.dir/test/feature_test.cpp.i
.PHONY : test/feature_test.cpp.i

test/feature_test.s: test/feature_test.cpp.s
.PHONY : test/feature_test.s

# target to generate assembly for a file
test/feature_test.cpp.s:
	$(MAKE) -f CMakeFiles/feature_test.dir/build.make CMakeFiles/feature_test.dir/test/feature_test.cpp.s
.PHONY : test/feature_test.cpp.s

test/pointcloud_test.o: test/pointcloud_test.cpp.o
.PHONY : test/pointcloud_test.o

# target to build an object file
test/pointcloud_test.cpp.o:
	$(MAKE) -f CMakeFiles/3d_test.dir/build.make CMakeFiles/3d_test.dir/test/pointcloud_test.cpp.o
.PHONY : test/pointcloud_test.cpp.o

test/pointcloud_test.i: test/pointcloud_test.cpp.i
.PHONY : test/pointcloud_test.i

# target to preprocess a source file
test/pointcloud_test.cpp.i:
	$(MAKE) -f CMakeFiles/3d_test.dir/build.make CMakeFiles/3d_test.dir/test/pointcloud_test.cpp.i
.PHONY : test/pointcloud_test.cpp.i

test/pointcloud_test.s: test/pointcloud_test.cpp.s
.PHONY : test/pointcloud_test.s

# target to generate assembly for a file
test/pointcloud_test.cpp.s:
	$(MAKE) -f CMakeFiles/3d_test.dir/build.make CMakeFiles/3d_test.dir/test/pointcloud_test.cpp.s
.PHONY : test/pointcloud_test.cpp.s

test/pointcloud_with_projection_test.o: test/pointcloud_with_projection_test.cpp.o
.PHONY : test/pointcloud_with_projection_test.o

# target to build an object file
test/pointcloud_with_projection_test.cpp.o:
	$(MAKE) -f CMakeFiles/3d_ptest.dir/build.make CMakeFiles/3d_ptest.dir/test/pointcloud_with_projection_test.cpp.o
.PHONY : test/pointcloud_with_projection_test.cpp.o

test/pointcloud_with_projection_test.i: test/pointcloud_with_projection_test.cpp.i
.PHONY : test/pointcloud_with_projection_test.i

# target to preprocess a source file
test/pointcloud_with_projection_test.cpp.i:
	$(MAKE) -f CMakeFiles/3d_ptest.dir/build.make CMakeFiles/3d_ptest.dir/test/pointcloud_with_projection_test.cpp.i
.PHONY : test/pointcloud_with_projection_test.cpp.i

test/pointcloud_with_projection_test.s: test/pointcloud_with_projection_test.cpp.s
.PHONY : test/pointcloud_with_projection_test.s

# target to generate assembly for a file
test/pointcloud_with_projection_test.cpp.s:
	$(MAKE) -f CMakeFiles/3d_ptest.dir/build.make CMakeFiles/3d_ptest.dir/test/pointcloud_with_projection_test.cpp.s
.PHONY : test/pointcloud_with_projection_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... 3d_ptest"
	@echo "... 3d_test"
	@echo "... edit_cache"
	@echo "... feature_test"
	@echo "... rebuild_cache"
	@echo "... features2d"
	@echo "... matchlib"
	@echo "... test/feature_test.o"
	@echo "... test/feature_test.i"
	@echo "... test/feature_test.s"
	@echo "... test/pointcloud_test.o"
	@echo "... test/pointcloud_test.i"
	@echo "... test/pointcloud_test.s"
	@echo "... test/pointcloud_with_projection_test.o"
	@echo "... test/pointcloud_with_projection_test.i"
	@echo "... test/pointcloud_with_projection_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

